-- ============================================================
-- INSERT tmacodigounidad1 — codigos deduplicados (primera
-- ocurrencia por Codigo). Idempotente: no inserta si ya existe.
-- ============================================================

;WITH datos AS (
    SELECT Codigo, Descripcion FROM (VALUES
        -- 1xxx — Gerencia / Administracion
        ('1000', 'GERENCIA GENERAL'),
        ('1100', 'AREA LEGAL'),
        ('1101', 'SUPERVISION'),
        ('1102', 'TALLER FLOTA LIVIANA'),
        ('1103', 'TALLER FLOTA PESADA'),
        ('1105', 'SSOMA'),
        ('1107', 'SERVICIOS GENERALES'),
        ('1108', 'MANTENIMIENTO'),
        ('1109', 'OPERACIONES'),
        ('1110', 'AUDITORIA INTERNA'),
        ('1111', 'ATENCION DE SINIESTRO'),
        ('1112', 'CONTABILIDAD'),
        ('1113', 'RRHH'),
        ('1114', 'AUDITORIA INTERNA'),
        ('1115', 'SSOMA'),
        ('1200', 'AUDITORIA INTERNA'),
        ('1300', 'PREVENCION DE RIESGO'),
        ('1301', 'SALUD OCUPACIONAL'),
        ('1800', 'MEJORA Y PROCESOS'),
        -- 2xxx — Administracion y Finanzas
        ('2000', 'GERENCIA DE ADMINISTRACION Y F'),
        ('2100', 'INFORMATICA'),
        ('2110', 'CONTABILIDAD'),
        ('2120', 'COMUNICACIONES'),
        ('2140', 'VIDEO VIGILANCIA'),
        ('2200', 'CONTABILIDAD'),
        ('2300', 'FINANZAS Y PRESUPUESTOS'),
        ('2400', 'RECURSOS HUMANOS'),
        ('2410', 'CAPACITACION EXTERNA'),
        ('2420', 'CAPACITACION INTERNA'),
        ('2430', 'SEGURIDAD PATRIMONIAL'),
        ('2500', 'SERVICIOS GENERALES'),
        ('2700', 'ALQUILER VEHICULOS ELECTRICOS'),
        ('2710', 'ALQUILER DE VEHICULOS Y MAQUINARIAS'),
        ('2800', 'PROYECTOS ERP'),
        -- 3xxx — Comercial / Transporte
        ('3000', 'GERENCIA COMERCIAL'),
        ('3050', 'VENTA MATERIALES TERCEROS'),
        ('3100', 'SERVICIOS INDUSTRIALES TERCEROS'),
        ('3101', 'VENTA DE SERVICIOS'),
        ('3111', 'TECSUR CAMIONETAS 4X2 ,COMBI,AUTOS'),
        ('3115', 'TECSUR CAMIONES CANTER PORTER'),
        ('3116', 'HITACHI RAIL'),
        ('3117', 'TORRE HOSPITALARIA COSAPI'),
        ('3118', 'HITACHI L2L4'),
        ('3124', 'TECSUR CAMIONETAS 4X4'),
        ('3126', 'TECSUR OTROS SERVICIOS'),
        ('3128', 'TECSUR CAMION TRACTO TERCERO'),
        ('3129', 'TECSUR GRUAS TERCEROS'),
        ('3131', 'TECSUR POOL'),
        ('3133', 'TECSUR GRUAS'),
        ('3134', 'TECSUR FLOTA LIVIANA TERCEROS'),
        ('3135', 'TECSUR CAMIONETAS TERCEROS'),
        ('3137', 'TECSUR CAMIONETAS ELECTRICAS'),
        ('3140', 'TECSUR GRUAS CORPORACION'),
        ('3141', 'TECSUR MANTENIMIENTO UNIDAD ELECTRICAS'),
        ('3142', 'TECSUR SINIESTRO'),
        ('3143', 'TECSUR IMPLEMENTACION'),
        ('3144', 'TECSUR OTROS MANTENIMIENTO'),
        ('3200', 'TRANSPORTE'),
        ('3201', 'ELECTROMOVILIDAD'),
        ('3202', 'ESTACION DE CARGA R3'),
        ('3203', 'ESTACION CAÑETE'),
        ('3204', 'ESTACION DE CARGA SAN BARTOLO'),
        ('3205', 'ESTACION DE CARGA SIGLO XXI'),
        ('3206', 'ESTACION DE CARGA CHOSICA'),
        ('3207', 'PROYECYO MAJES'),
        ('3212', 'LDS BRAZOS HIDRAULICOS'),
        ('3213', 'LDS CAMIONETAS 4X2'),
        ('3214', 'LDS CAMIONETAS 4X4'),
        ('3215', 'LDS CAMIONETAS Y AUTOS POOL'),
        ('3217', 'LDS GRUAS'),
        ('3218', 'LDS OTROS SERVICIOS'),
        ('3220', 'LDS GRUAS TERCEROS'),
        ('3221', 'LDS CAMION TRACTO TERCEROS'),
        ('3222', 'LDS CAMIONES'),
        ('3234', 'LDS FLOTA LIVIANA TERCEROS'),
        ('3235', 'LDS CAMIONETAS TERCEROS'),
        ('3236', 'LDS BRAZOS AISLADO CORPORACION'),
        ('3237', 'LDS CAMIONETAS ELECTRICAS'),
        ('3238', 'LDS CAMIONETAS DIESEL FORD'),
        ('3240', 'LDS GRUAS CORPORACION'),
        ('3241', 'LDS CAMION PORTER DIESEL'),
        ('3242', 'LDS SINIESTROS'),
        ('3243', 'LDS IMPLEMENTACION'),
        ('3244', 'LDS OTROS MANTENIMIENTOS'),
        ('3245', 'LDS CAMIONETA HIBRIDA 4X4'),
        ('3246', 'LDS BRAZO AISLADO HIDROLAVADOR TERCEROS'),
        ('3300', 'GESTION DE PROYECTOS'),
        ('3318', 'GCI CAMIONETAS 4X2'),
        ('3320', 'GCI CAMIONES CANTER, PORTER'),
        ('3321', 'GCI BRAZOS HIDRAULICOS'),
        ('3322', 'GCI OTROS SERVICIOS'),
        ('3325', 'GCI CAMIONETAS 4X4'),
        ('3327', 'GCI GRUAS'),
        ('3328', 'GCI GRUAS TERCEROS'),
        ('3329', 'GCI CAMION TRACTO TERCEROS'),
        ('3331', 'GCI POOL'),
        ('3335', 'GCI CAMIONETAS TERCEROS'),
        ('3337', 'GCI CAMIONETAS ELECTRICAS'),
        ('3338', 'GCI CAMIONETAS DIESEL FORD'),
        ('3339', 'GCI CAMIONES ELECTRICOS'),
        ('3340', 'GCI GRUAS 8TN'),
        ('3342', 'GCI SINIESTRO'),
        ('3343', 'GCI IMPLEMENTACION'),
        ('3344', 'GCI OTROS MANTENIMIENTO'),
        ('3400', 'MARKETING'),
        ('3410', 'TERCEROS GRUAS'),
        ('3430', 'TERCEROS OTROS'),
        ('3440', 'TERCEROS FLOTA PROPIA'),
        ('3500', 'TRANSPORTE APIM'),
        ('3510', 'APIM MINIBUS EV'),
        ('3520', 'APIM SINIESTROS'),
        ('3530', 'APIM IMPLEMENTACION'),
        ('3540', 'APIM OTROS MANTENIMIENTO'),
        -- 4xxx — Operaciones
        ('4000', 'GERENCIA DE OPERACIO'),
        ('4040', 'PROYECTOS Y SISTEMAS DE UTILIZACION'),
        ('4050', 'GESTION DE PROYECTOS'),
        ('4060', 'INGENIERIA'),
        ('4220', 'EMERGENCIA Y ALUMBRADO'),
        ('4230', 'MANTENIMIENTO DISTRIBUCION'),
        ('4235', 'MANTENIMIENTO MEDIA TENSION'),
        ('4300', 'OBRAS MEDIA TENSION'),
        ('4301', 'OBRAS BAJA TENSION'),
        ('4440', 'OPERACIONES CAÑETE'),
        ('4620', 'OTROS SERVICIOS LDS'),
        ('4700', 'CONTROL DE OBRAS'),
        ('4800', 'EJECUCION DE OBRAS'),
        ('4805', 'MANTENIMIENTO AP'),
        ('4808', 'PROYECTOS MT'),
        ('4900', 'SET PACHACUTEC - DIRECCION'),
        ('4904', 'PROYECTOS TRANSMISION'),
        ('4905', 'MANTENIMIENTO TRANSMISION'),
        -- 5xxx — Logistica / Ventas / Servicios de campo
        ('5000', 'GERENCIA DE LOGISTICA'),
        ('5100', 'COMPRAS'),
        ('5200', 'ALMACENES'),
        ('5210', 'ALMACENES LDS'),
        ('5240', 'MEDIDORES'),
        ('5320', 'RECLAMOS AP LIMA'),
        ('5330', 'RECLAMOS BT LIMA'),
        ('5333', 'VERIFICACION REDES'),
        ('5340', 'EMERGENCIA LIMA'),
        ('5360', 'FUGAS A TIERRA'),
        ('5361', 'REFORMA MANTENIMIENTO SUBTERRANEA'),
        ('5370', 'MANTENIMIENTO DE MEDIA TENSION'),
        ('5371', 'PROYECTOS BAJA TENSION'),
        ('5372', 'MTO PAT / MTO RETENIDAS'),
        ('5373', 'PEM'),
        ('5376', 'SED'),
        ('5377', 'PODA'),
        ('5378', 'LAVADO'),
        ('5380', 'CONEXIONES DE RUTINA'),
        ('5390', 'PROYECTOS MEDIA TENSIÓN'),
        ('5400', 'METROLOGIA'),
        ('5410', 'CONTROL DE CALIDAD'),
        ('5420', 'MANTENIMIENTO Y PROYECTOS MT'),
        ('5430', 'RECLAMOS BT - CAÑETE'),
        ('5440', 'EMERGENCIA - CAÑETE'),
        ('5450', 'MANTENIMIENTO Y PROYECTOS BT'),
        ('5500', 'VENTAS LUZ DEL SUR'),
        ('5511', 'CAMBIO DE POSTES'),
        ('5530', 'MATERIALES CONTRATISTAS'),
        ('5540', 'DESMEDRO'),
        ('5600', 'VENTAS LOS ANDES'),
        ('5620', 'VENTA GCI'),
        ('5700', 'RECICLAJE'),
        ('5710', 'MATERIALES OBSOLETOS RECICLAJE'),
        ('5720', 'LUMINARIAS REHABILITADAS'),
        ('5730', 'MUESTREO Y REMEDIACION'),
        ('5740', 'VENTA MATERIAL RECICLADO'),
        ('5760', 'TRANSFORMADORES'),
        ('5780', 'RAEE'),
        -- 6xxx — Nivel empresa
        ('6000', 'NIVEL EMPRESA'),
        -- 7xxx — Servicios / Oficina tecnica
        ('7400', 'SERVICIOS TERCEROS'),
        ('7500', 'OFICINA TECNICA'),
        ('7600', 'VENTA TECSUR')
    ) AS t(Codigo, Descripcion)
)
MERGE tmacodigounidad1 AS target
USING datos AS source ON target.Codigo = source.Codigo
WHEN NOT MATCHED THEN
    INSERT (Codigo, Descripcion, Empresa, Activo, UsuarioReg, FechaReg)
    VALUES (source.Codigo, source.Descripcion, '', 1, 'SISTEMA', GETDATE());
GO
